// Mux Go - Copyright 2019 Mux Inc.
// NOTE: This file is auto generated. Do not edit this file manually.

package muxgo

// SpaceStatus : The status of the space. Spaces are `idle` when there are no participants connected, and `active` when there are participants connected.
type SpaceStatus string

// List of SpaceStatus
const (
	SPACE_IDLE   SpaceStatus = "idle"
	SPACE_ACTIVE SpaceStatus = "active"
)
