/*
 * Mux API
 *
 * Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.
 *
 * API version: v1
 * Contact: devex@mux.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package muxgo

import (
	"encoding/json"
)

// DisableLiveStreamResponse struct for DisableLiveStreamResponse
type DisableLiveStreamResponse struct {
	Data *map[string]interface{} `json:"data,omitempty"`
}

// NewDisableLiveStreamResponse instantiates a new DisableLiveStreamResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDisableLiveStreamResponse() *DisableLiveStreamResponse {
	this := DisableLiveStreamResponse{}
	return &this
}

// NewDisableLiveStreamResponseWithDefaults instantiates a new DisableLiveStreamResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDisableLiveStreamResponseWithDefaults() *DisableLiveStreamResponse {
	this := DisableLiveStreamResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *DisableLiveStreamResponse) GetData() map[string]interface{} {
	if o == nil || o.Data == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisableLiveStreamResponse) GetDataOk() (*map[string]interface{}, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *DisableLiveStreamResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *DisableLiveStreamResponse) SetData(v map[string]interface{}) {
	o.Data = &v
}

func (o DisableLiveStreamResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableDisableLiveStreamResponse struct {
	value *DisableLiveStreamResponse
	isSet bool
}

func (v NullableDisableLiveStreamResponse) Get() *DisableLiveStreamResponse {
	return v.value
}

func (v *NullableDisableLiveStreamResponse) Set(val *DisableLiveStreamResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDisableLiveStreamResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDisableLiveStreamResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDisableLiveStreamResponse(val *DisableLiveStreamResponse) *NullableDisableLiveStreamResponse {
	return &NullableDisableLiveStreamResponse{value: val, isSet: true}
}

func (v NullableDisableLiveStreamResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDisableLiveStreamResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


