// Mux Go - Copyright 2019 Mux Inc.
// NOTE: This file is auto generated. Do not edit this file manually.

package muxgo

type IncidentNotificationRule struct {
	Status     string             `json:"status,omitempty"`
	Rules      []NotificationRule `json:"rules,omitempty"`
	PropertyId string             `json:"property_id,omitempty"`
	Id         string             `json:"id,omitempty"`
	Action     string             `json:"action,omitempty"`
}
