// Mux Go - Copyright 2019 Mux Inc.
// NOTE: This file is auto generated. Do not edit this file manually.

package muxgo

// LiveStreamStatus : `idle` indicates that there is no active broadcast. `active` indicates that there is an active broadcast and `disabled` status indicates that no future RTMP streams can be published.
type LiveStreamStatus string

// List of LiveStreamStatus
const (
	ACTIVE   LiveStreamStatus = "active"
	IDLE     LiveStreamStatus = "idle"
	DISABLED LiveStreamStatus = "disabled"
)
