/*
 * Mux Video
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package muxvideosdk

type ListInsightsResponse struct {
	Data []Insight `json:"data,omitempty"`
	TotalRowCount int32 `json:"total_row_count,omitempty"`
	Timeframe []string `json:"timeframe,omitempty"`
}
