/*
 * Mux Video
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package muxvideosdk

type FilterValue struct {
	Value string `json:"value,omitempty"`
	TotalCount int32 `json:"total_count,omitempty"`
}
