/*
 * Mux API
 *
 * Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.
 *
 * API version: v1
 * Contact: devex@mux.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package muxgo

import (
	"encoding/json"
)

// GetAssetPlaybackIDResponse struct for GetAssetPlaybackIDResponse
type GetAssetPlaybackIDResponse struct {
	Data *PlaybackID `json:"data,omitempty"`
}

// NewGetAssetPlaybackIDResponse instantiates a new GetAssetPlaybackIDResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAssetPlaybackIDResponse() *GetAssetPlaybackIDResponse {
	this := GetAssetPlaybackIDResponse{}
	return &this
}

// NewGetAssetPlaybackIDResponseWithDefaults instantiates a new GetAssetPlaybackIDResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAssetPlaybackIDResponseWithDefaults() *GetAssetPlaybackIDResponse {
	this := GetAssetPlaybackIDResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetAssetPlaybackIDResponse) GetData() PlaybackID {
	if o == nil || o.Data == nil {
		var ret PlaybackID
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAssetPlaybackIDResponse) GetDataOk() (*PlaybackID, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetAssetPlaybackIDResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given PlaybackID and assigns it to the Data field.
func (o *GetAssetPlaybackIDResponse) SetData(v PlaybackID) {
	o.Data = &v
}

func (o GetAssetPlaybackIDResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetAssetPlaybackIDResponse struct {
	value *GetAssetPlaybackIDResponse
	isSet bool
}

func (v NullableGetAssetPlaybackIDResponse) Get() *GetAssetPlaybackIDResponse {
	return v.value
}

func (v *NullableGetAssetPlaybackIDResponse) Set(val *GetAssetPlaybackIDResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAssetPlaybackIDResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAssetPlaybackIDResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAssetPlaybackIDResponse(val *GetAssetPlaybackIDResponse) *NullableGetAssetPlaybackIDResponse {
	return &NullableGetAssetPlaybackIDResponse{value: val, isSet: true}
}

func (v NullableGetAssetPlaybackIDResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAssetPlaybackIDResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


