// Mux Go - Copyright 2019 Mux Inc.
// NOTE: This file is auto generated. Do not edit this file manually.

package muxgo

type UpdateLiveStreamEmbeddedSubtitlesRequest struct {
	// Describe the embedded subtitle contents of the incoming live stream.
	EmbeddedSubtitles []LiveStreamEmbeddedSubtitleSettings `json:"embedded_subtitles,omitempty"`
}
