/*
 * Mux API
 *
 * Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.
 *
 * API version: v1
 * Contact: devex@mux.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package muxgo

import (
	"encoding/json"
)

// PlaybackID struct for PlaybackID
type PlaybackID struct {
	// Unique identifier for the PlaybackID
	Id *string `json:"id,omitempty"`
	Policy *PlaybackPolicy `json:"policy,omitempty"`
}

// NewPlaybackID instantiates a new PlaybackID object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaybackID() *PlaybackID {
	this := PlaybackID{}
	return &this
}

// NewPlaybackIDWithDefaults instantiates a new PlaybackID object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaybackIDWithDefaults() *PlaybackID {
	this := PlaybackID{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PlaybackID) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaybackID) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PlaybackID) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PlaybackID) SetId(v string) {
	o.Id = &v
}

// GetPolicy returns the Policy field value if set, zero value otherwise.
func (o *PlaybackID) GetPolicy() PlaybackPolicy {
	if o == nil || o.Policy == nil {
		var ret PlaybackPolicy
		return ret
	}
	return *o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaybackID) GetPolicyOk() (*PlaybackPolicy, bool) {
	if o == nil || o.Policy == nil {
		return nil, false
	}
	return o.Policy, true
}

// HasPolicy returns a boolean if a field has been set.
func (o *PlaybackID) HasPolicy() bool {
	if o != nil && o.Policy != nil {
		return true
	}

	return false
}

// SetPolicy gets a reference to the given PlaybackPolicy and assigns it to the Policy field.
func (o *PlaybackID) SetPolicy(v PlaybackPolicy) {
	o.Policy = &v
}

func (o PlaybackID) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Policy != nil {
		toSerialize["policy"] = o.Policy
	}
	return json.Marshal(toSerialize)
}

type NullablePlaybackID struct {
	value *PlaybackID
	isSet bool
}

func (v NullablePlaybackID) Get() *PlaybackID {
	return v.value
}

func (v *NullablePlaybackID) Set(val *PlaybackID) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaybackID) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaybackID) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaybackID(val *PlaybackID) *NullablePlaybackID {
	return &NullablePlaybackID{value: val, isSet: true}
}

func (v NullablePlaybackID) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlaybackID) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


