/*
 * Mux API
 *
 * Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.
 *
 * API version: v1
 * Contact: devex@mux.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package muxgo

import (
	"encoding/json"
)

// ListVideoViewExportsResponse struct for ListVideoViewExportsResponse
type ListVideoViewExportsResponse struct {
	Data *[]ExportDate `json:"data,omitempty"`
	TotalRowCount *int32 `json:"total_row_count,omitempty"`
	Timeframe *[]int32 `json:"timeframe,omitempty"`
}

// NewListVideoViewExportsResponse instantiates a new ListVideoViewExportsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListVideoViewExportsResponse() *ListVideoViewExportsResponse {
	this := ListVideoViewExportsResponse{}
	return &this
}

// NewListVideoViewExportsResponseWithDefaults instantiates a new ListVideoViewExportsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListVideoViewExportsResponseWithDefaults() *ListVideoViewExportsResponse {
	this := ListVideoViewExportsResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListVideoViewExportsResponse) GetData() []ExportDate {
	if o == nil || o.Data == nil {
		var ret []ExportDate
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListVideoViewExportsResponse) GetDataOk() (*[]ExportDate, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListVideoViewExportsResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []ExportDate and assigns it to the Data field.
func (o *ListVideoViewExportsResponse) SetData(v []ExportDate) {
	o.Data = &v
}

// GetTotalRowCount returns the TotalRowCount field value if set, zero value otherwise.
func (o *ListVideoViewExportsResponse) GetTotalRowCount() int32 {
	if o == nil || o.TotalRowCount == nil {
		var ret int32
		return ret
	}
	return *o.TotalRowCount
}

// GetTotalRowCountOk returns a tuple with the TotalRowCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListVideoViewExportsResponse) GetTotalRowCountOk() (*int32, bool) {
	if o == nil || o.TotalRowCount == nil {
		return nil, false
	}
	return o.TotalRowCount, true
}

// HasTotalRowCount returns a boolean if a field has been set.
func (o *ListVideoViewExportsResponse) HasTotalRowCount() bool {
	if o != nil && o.TotalRowCount != nil {
		return true
	}

	return false
}

// SetTotalRowCount gets a reference to the given int32 and assigns it to the TotalRowCount field.
func (o *ListVideoViewExportsResponse) SetTotalRowCount(v int32) {
	o.TotalRowCount = &v
}

// GetTimeframe returns the Timeframe field value if set, zero value otherwise.
func (o *ListVideoViewExportsResponse) GetTimeframe() []int32 {
	if o == nil || o.Timeframe == nil {
		var ret []int32
		return ret
	}
	return *o.Timeframe
}

// GetTimeframeOk returns a tuple with the Timeframe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListVideoViewExportsResponse) GetTimeframeOk() (*[]int32, bool) {
	if o == nil || o.Timeframe == nil {
		return nil, false
	}
	return o.Timeframe, true
}

// HasTimeframe returns a boolean if a field has been set.
func (o *ListVideoViewExportsResponse) HasTimeframe() bool {
	if o != nil && o.Timeframe != nil {
		return true
	}

	return false
}

// SetTimeframe gets a reference to the given []int32 and assigns it to the Timeframe field.
func (o *ListVideoViewExportsResponse) SetTimeframe(v []int32) {
	o.Timeframe = &v
}

func (o ListVideoViewExportsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.TotalRowCount != nil {
		toSerialize["total_row_count"] = o.TotalRowCount
	}
	if o.Timeframe != nil {
		toSerialize["timeframe"] = o.Timeframe
	}
	return json.Marshal(toSerialize)
}

type NullableListVideoViewExportsResponse struct {
	value *ListVideoViewExportsResponse
	isSet bool
}

func (v NullableListVideoViewExportsResponse) Get() *ListVideoViewExportsResponse {
	return v.value
}

func (v *NullableListVideoViewExportsResponse) Set(val *ListVideoViewExportsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListVideoViewExportsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListVideoViewExportsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListVideoViewExportsResponse(val *ListVideoViewExportsResponse) *NullableListVideoViewExportsResponse {
	return &NullableListVideoViewExportsResponse{value: val, isSet: true}
}

func (v NullableListVideoViewExportsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListVideoViewExportsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


