// Mux Go - Copyright 2019 Mux Inc.
// NOTE: This file is auto generated. Do not edit this file manually.

package muxgo

type ListAnnotationsResponse struct {
	Data []Annotation `json:"data,omitempty"`
	// Total number of annotations available
	TotalRowCount int32 `json:"total_row_count,omitempty"`
	// Start and end unix timestamps for the data range
	Timeframe []int32 `json:"timeframe,omitempty"`
}
