// Mux Go - Copyright 2019 Mux Inc.
// NOTE: This file is auto generated. Do not edit this file manually.

package muxgo

type AssetGeneratedSubtitleSettings struct {
	// A name for this subtitle track.
	Name string `json:"name,omitempty"`
	// Arbitrary metadata set for the subtitle track. Max 255 characters.
	Passthrough string `json:"passthrough,omitempty"`
	// The language to generate subtitles in.
	LanguageCode string `json:"language_code,omitempty"`
}
