// Mux Go - Copyright 2019 Mux Inc.
// NOTE: This file is auto generated. Do not edit this file manually.

package muxgo

type MonitoringTimeseriesDatapoint struct {
	Value             float64 `json:"value,omitempty"`
	Date              string  `json:"date,omitempty"`
	ConcurrentViewers int64   `json:"concurrent_viewers,omitempty"`
}
