// Mux Go - Copyright 2019 Mux Inc.
// NOTE: This file is auto generated. Do not edit this file manually.

package muxgo

type SigningKeyCreateResponse struct {
	Data SigningKey `json:"data,omitempty"`
}
