/*
 * Mux API
 *
 * Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.
 *
 * API version: v1
 * Contact: devex@mux.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package muxgo

import (
	"encoding/json"
)

// CreatePlaybackIDResponse struct for CreatePlaybackIDResponse
type CreatePlaybackIDResponse struct {
	Data *PlaybackID `json:"data,omitempty"`
}

// NewCreatePlaybackIDResponse instantiates a new CreatePlaybackIDResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePlaybackIDResponse() *CreatePlaybackIDResponse {
	this := CreatePlaybackIDResponse{}
	return &this
}

// NewCreatePlaybackIDResponseWithDefaults instantiates a new CreatePlaybackIDResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePlaybackIDResponseWithDefaults() *CreatePlaybackIDResponse {
	this := CreatePlaybackIDResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreatePlaybackIDResponse) GetData() PlaybackID {
	if o == nil || o.Data == nil {
		var ret PlaybackID
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePlaybackIDResponse) GetDataOk() (*PlaybackID, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreatePlaybackIDResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given PlaybackID and assigns it to the Data field.
func (o *CreatePlaybackIDResponse) SetData(v PlaybackID) {
	o.Data = &v
}

func (o CreatePlaybackIDResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableCreatePlaybackIDResponse struct {
	value *CreatePlaybackIDResponse
	isSet bool
}

func (v NullableCreatePlaybackIDResponse) Get() *CreatePlaybackIDResponse {
	return v.value
}

func (v *NullableCreatePlaybackIDResponse) Set(val *CreatePlaybackIDResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePlaybackIDResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePlaybackIDResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePlaybackIDResponse(val *CreatePlaybackIDResponse) *NullableCreatePlaybackIDResponse {
	return &NullableCreatePlaybackIDResponse{value: val, isSet: true}
}

func (v NullableCreatePlaybackIDResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePlaybackIDResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


