// Mux Go - Copyright 2019 Mux Inc.
// NOTE: This file is auto generated. Do not edit this file manually.

package muxgo

type PlaybackId struct {
	// Unique identifier for the PlaybackID
	Id     string         `json:"id,omitempty"`
	Policy PlaybackPolicy `json:"policy,omitempty"`
	// The DRM configuration used by this playback ID. Must only be set when `policy` is set to `drm`.
	DrmConfigurationId string `json:"drm_configuration_id,omitempty"`
}
