/*
 * Mux API
 *
 * Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.
 *
 * API version: v1
 * Contact: devex@mux.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package muxgo

import (
	"encoding/json"
)

// UploadError Only set if an error occurred during asset creation.
type UploadError struct {
	// Label for the specific error
	Type *string `json:"type,omitempty"`
	// Human readable error message
	Message *string `json:"message,omitempty"`
}

// NewUploadError instantiates a new UploadError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadError() *UploadError {
	this := UploadError{}
	return &this
}

// NewUploadErrorWithDefaults instantiates a new UploadError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadErrorWithDefaults() *UploadError {
	this := UploadError{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *UploadError) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadError) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *UploadError) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *UploadError) SetType(v string) {
	o.Type = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *UploadError) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadError) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *UploadError) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *UploadError) SetMessage(v string) {
	o.Message = &v
}

func (o UploadError) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableUploadError struct {
	value *UploadError
	isSet bool
}

func (v NullableUploadError) Get() *UploadError {
	return v.value
}

func (v *NullableUploadError) Set(val *UploadError) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadError) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadError(val *UploadError) *NullableUploadError {
	return &NullableUploadError{value: val, isSet: true}
}

func (v NullableUploadError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


