// Mux Go - Copyright 2019 Mux Inc.
// NOTE: This file is auto generated. Do not edit this file manually.

package muxgo

import (
	"time"
)

type AssetRecordingTimes struct {
	// The time at which the recording for the live stream started. The time value is Unix epoch time represented in ISO 8601 format.
	StartedAt time.Time `json:"started_at,omitempty"`
	// The duration of the live stream recorded. The time value is in seconds.
	Duration float64 `json:"duration,omitempty"`
	// The type of media represented by the recording session, either `content` for normal stream content or `slate` for slate media inserted during stream interruptions.
	Type string `json:"type,omitempty"`
}
