// Mux Go - Copyright 2019 Mux Inc.
// NOTE: This file is auto generated. Do not edit this file manually.

package muxgo

type CreateWebInputRequest struct {
	// Unique identifier for the Web Input.
	Id string `json:"id,omitempty"`
	// Time the Web Input was created, defined as a Unix timestamp (seconds since epoch).
	CreatedAt string `json:"created_at,omitempty"`
	// The URL for the Web Input to load.
	Url string `json:"url,omitempty"`
	// When set to `true` the Web Input will automatically launch and start streaming immediately after creation
	AutoLaunch bool `json:"auto_launch,omitempty"`
	// The Live Stream ID to broadcast this Web Input to
	LiveStreamId string `json:"live_stream_id,omitempty"`
	Status       string `json:"status,omitempty"`
	// Arbitrary metadata that will be included in the Web Input details and related webhooks. Can be used to store your own ID for the Web Input. **Max: 255 characters**.
	Passthrough string `json:"passthrough,omitempty"`
	// The resolution of the viewport of the Web Input's browser instance. Defaults to 1920x1080 if not set.
	Resolution string `json:"resolution,omitempty"`
	// The number of seconds that the Web Input should stream for before automatically shutting down.
	Timeout int32 `json:"timeout,omitempty"`
}
