// Mux Go - Copyright 2019 Mux Inc.
// NOTE: This file is auto generated. Do not edit this file manually.

package muxgo

type IncidentResponse struct {
	Data      Incident `json:"data,omitempty"`
	Timeframe []int64  `json:"timeframe,omitempty"`
}
