// Mux Go - Copyright 2019 Mux Inc.
// NOTE: This file is auto generated. Do not edit this file manually.

package muxgo

type GenerateTrackSubtitlesRequest struct {
	// Generate subtitle tracks using automatic speech recognition with this configuration.
	GeneratedSubtitles []AssetGeneratedSubtitleSettings `json:"generated_subtitles,omitempty"`
}
