// Mux Go - Copyright 2019 Mux Inc.
// NOTE: This file is auto generated. Do not edit this file manually.

package muxvideosdk

type GetAssetPlaybackIdResponse struct {
	Data PlaybackId `json:"data,omitempty"`
}
