/*
 * Mux Video
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package muxvideosdk

type AssetErrors struct {
	Type string `json:"type,omitempty"`
	Messages []string `json:"messages,omitempty"`
}
