// Mux Go - Copyright 2019 Mux Inc.
// NOTE: This file is auto generated. Do not edit this file manually.

package muxgo

// BroadcastResolution : The resolution of the composited video sent to the live stream. Defaults to `1920x1080` if not set.
type BroadcastResolution string

// List of BroadcastResolution
const (
	_1920X1080 BroadcastResolution = "1920x1080"
	_1280X720  BroadcastResolution = "1280x720"
	_1080X1920 BroadcastResolution = "1080x1920"
	_720X1280  BroadcastResolution = "720x1280"
	_1080X1080 BroadcastResolution = "1080x1080"
	_720X720   BroadcastResolution = "720x720"
)
