/*
 * Mux API
 *
 * Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before. 
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package muxgo

import (
	"encoding/json"
)

// GetRealTimeHistogramTimeseriesResponseMeta struct for GetRealTimeHistogramTimeseriesResponseMeta
type GetRealTimeHistogramTimeseriesResponseMeta struct {
	Buckets *[]RealTimeHistogramTimeseriesBucket `json:"buckets,omitempty"`
}

// NewGetRealTimeHistogramTimeseriesResponseMeta instantiates a new GetRealTimeHistogramTimeseriesResponseMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRealTimeHistogramTimeseriesResponseMeta() *GetRealTimeHistogramTimeseriesResponseMeta {
	this := GetRealTimeHistogramTimeseriesResponseMeta{}
	return &this
}

// NewGetRealTimeHistogramTimeseriesResponseMetaWithDefaults instantiates a new GetRealTimeHistogramTimeseriesResponseMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRealTimeHistogramTimeseriesResponseMetaWithDefaults() *GetRealTimeHistogramTimeseriesResponseMeta {
	this := GetRealTimeHistogramTimeseriesResponseMeta{}
	return &this
}

// GetBuckets returns the Buckets field value if set, zero value otherwise.
func (o *GetRealTimeHistogramTimeseriesResponseMeta) GetBuckets() []RealTimeHistogramTimeseriesBucket {
	if o == nil || o.Buckets == nil {
		var ret []RealTimeHistogramTimeseriesBucket
		return ret
	}
	return *o.Buckets
}

// GetBucketsOk returns a tuple with the Buckets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRealTimeHistogramTimeseriesResponseMeta) GetBucketsOk() (*[]RealTimeHistogramTimeseriesBucket, bool) {
	if o == nil || o.Buckets == nil {
		return nil, false
	}
	return o.Buckets, true
}

// HasBuckets returns a boolean if a field has been set.
func (o *GetRealTimeHistogramTimeseriesResponseMeta) HasBuckets() bool {
	if o != nil && o.Buckets != nil {
		return true
	}

	return false
}

// SetBuckets gets a reference to the given []RealTimeHistogramTimeseriesBucket and assigns it to the Buckets field.
func (o *GetRealTimeHistogramTimeseriesResponseMeta) SetBuckets(v []RealTimeHistogramTimeseriesBucket) {
	o.Buckets = &v
}

func (o GetRealTimeHistogramTimeseriesResponseMeta) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Buckets != nil {
		toSerialize["buckets"] = o.Buckets
	}
	return json.Marshal(toSerialize)
}

type NullableGetRealTimeHistogramTimeseriesResponseMeta struct {
	value *GetRealTimeHistogramTimeseriesResponseMeta
	isSet bool
}

func (v NullableGetRealTimeHistogramTimeseriesResponseMeta) Get() *GetRealTimeHistogramTimeseriesResponseMeta {
	return v.value
}

func (v *NullableGetRealTimeHistogramTimeseriesResponseMeta) Set(val *GetRealTimeHistogramTimeseriesResponseMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRealTimeHistogramTimeseriesResponseMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRealTimeHistogramTimeseriesResponseMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRealTimeHistogramTimeseriesResponseMeta(val *GetRealTimeHistogramTimeseriesResponseMeta) *NullableGetRealTimeHistogramTimeseriesResponseMeta {
	return &NullableGetRealTimeHistogramTimeseriesResponseMeta{value: val, isSet: true}
}

func (v NullableGetRealTimeHistogramTimeseriesResponseMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRealTimeHistogramTimeseriesResponseMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


