// Mux Go - Copyright 2019 Mux Inc.
// NOTE: This file is auto generated. Do not edit this file manually.

package muxgo

// Only set if an error occurred during asset creation.
type UploadError struct {
	Type string `json:"type,omitempty"`
	Message string `json:"message,omitempty"`
}
