// Mux Go - Copyright 2019 Mux Inc.
// NOTE: This file is auto generated. Do not edit this file manually.

package muxgo

type SimulcastTargetResponse struct {
	Data SimulcastTarget `json:"data,omitempty"`
}
