// Mux Go - Copyright 2019 Mux Inc.
// NOTE: This file is auto generated. Do not edit this file manually.

package muxgo

type DrmConfiguration struct {
	// Unique identifier for the DRM Configuration. Max 255 characters.
	Id string `json:"id,omitempty"`
}
