// Mux Go - Copyright 2019 Mux Inc.
// NOTE: This file is auto generated. Do not edit this file manually.

package muxgo

type RealTimeBreakdownValue struct {
	Value            string  `json:"value,omitempty"`
	NegativeImpact   int64   `json:"negative_impact,omitempty"`
	MetricValue      float64 `json:"metric_value,omitempty"`
	DisplayValue     string  `json:"display_value,omitempty"`
	ConcurentViewers int64   `json:"concurent_viewers,omitempty"`
}
