// Mux Go - Copyright 2019 Mux Inc.
// NOTE: This file is auto generated. Do not edit this file manually.

package muxgo

type InputInfo struct {
	Settings InputSettings `json:"settings,omitempty"`
	File     InputFile     `json:"file,omitempty"`
}
