// Mux Go - Copyright 2019 Mux Inc.
// NOTE: This file is auto generated. Do not edit this file manually.

package muxgo

type PlaybackId struct {
	Id     string         `json:"id,omitempty"`
	Policy PlaybackPolicy `json:"policy,omitempty"`
}
