// Mux Go - Copyright 2019 Mux Inc.
// NOTE: This file is auto generated. Do not edit this file manually.

package muxgo

type TranscriptionVocabulary struct {
	// Unique identifier for the Transcription Vocabulary
	Id string `json:"id,omitempty"`
	// The user-supplied name of the Transcription Vocabulary.
	Name string `json:"name,omitempty"`
	// Phrases, individual words, or proper names to include in the Transcription Vocabulary. When the Transcription Vocabulary is attached to a live stream's `generated_subtitles` configuration, the probability of successful speech recognition for these words or phrases is boosted.
	Phrases []string `json:"phrases,omitempty"`
	// Arbitrary user-supplied metadata set for the Transcription Vocabulary. Max 255 characters.
	Passthrough string `json:"passthrough,omitempty"`
	// Time the Transcription Vocabulary was created, defined as a Unix timestamp (seconds since epoch).
	CreatedAt string `json:"created_at,omitempty"`
	// Time the Transcription Vocabulary was updated, defined as a Unix timestamp (seconds since epoch).
	UpdatedAt string `json:"updated_at,omitempty"`
}
