/*
 * Mux Video
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package muxvideosdk

// Only set if an error occurred during asset creation.
type UploadError struct {
	Type string `json:"type,omitempty"`
	Message string `json:"message,omitempty"`
}
