// Mux Go - Copyright 2019 Mux Inc.
// NOTE: This file is auto generated. Do not edit this file manually.

package muxgo

type IncidentBreakdown struct {
	Value string `json:"value,omitempty"`
	Name  string `json:"name,omitempty"`
	Id    string `json:"id,omitempty"`
}
