/*
 * Mux API
 *
 * Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before. 
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package muxgo

import (
	"encoding/json"
)

// IncidentBreakdown struct for IncidentBreakdown
type IncidentBreakdown struct {
	Value *string `json:"value,omitempty"`
	Name *string `json:"name,omitempty"`
	Id *string `json:"id,omitempty"`
}

// NewIncidentBreakdown instantiates a new IncidentBreakdown object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIncidentBreakdown() *IncidentBreakdown {
	this := IncidentBreakdown{}
	return &this
}

// NewIncidentBreakdownWithDefaults instantiates a new IncidentBreakdown object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIncidentBreakdownWithDefaults() *IncidentBreakdown {
	this := IncidentBreakdown{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *IncidentBreakdown) GetValue() string {
	if o == nil || o.Value == nil {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentBreakdown) GetValueOk() (*string, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *IncidentBreakdown) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *IncidentBreakdown) SetValue(v string) {
	o.Value = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *IncidentBreakdown) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentBreakdown) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *IncidentBreakdown) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *IncidentBreakdown) SetName(v string) {
	o.Name = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *IncidentBreakdown) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentBreakdown) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *IncidentBreakdown) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *IncidentBreakdown) SetId(v string) {
	o.Id = &v
}

func (o IncidentBreakdown) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableIncidentBreakdown struct {
	value *IncidentBreakdown
	isSet bool
}

func (v NullableIncidentBreakdown) Get() *IncidentBreakdown {
	return v.value
}

func (v *NullableIncidentBreakdown) Set(val *IncidentBreakdown) {
	v.value = val
	v.isSet = true
}

func (v NullableIncidentBreakdown) IsSet() bool {
	return v.isSet
}

func (v *NullableIncidentBreakdown) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIncidentBreakdown(val *IncidentBreakdown) *NullableIncidentBreakdown {
	return &NullableIncidentBreakdown{value: val, isSet: true}
}

func (v NullableIncidentBreakdown) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIncidentBreakdown) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


