// Mux Go - Copyright 2019 Mux Inc.
// NOTE: This file is auto generated. Do not edit this file manually.

package muxgo

type Incident struct {
	Threshold                  float64                    `json:"threshold,omitempty"`
	Status                     string                     `json:"status,omitempty"`
	StartedAt                  string                     `json:"started_at,omitempty"`
	Severity                   string                     `json:"severity,omitempty"`
	SampleSizeUnit             string                     `json:"sample_size_unit,omitempty"`
	SampleSize                 int64                      `json:"sample_size,omitempty"`
	ResolvedAt                 string                     `json:"resolved_at,omitempty"`
	Notifications              []IncidentNotification     `json:"notifications,omitempty"`
	NotificationRules          []IncidentNotificationRule `json:"notification_rules,omitempty"`
	Measurement                string                     `json:"measurement,omitempty"`
	MeasuredValueOnClose       float64                    `json:"measured_value_on_close,omitempty"`
	MeasuredValue              float64                    `json:"measured_value,omitempty"`
	IncidentKey                string                     `json:"incident_key,omitempty"`
	Impact                     string                     `json:"impact,omitempty"`
	Id                         string                     `json:"id,omitempty"`
	ErrorDescription           string                     `json:"error_description,omitempty"`
	Description                string                     `json:"description,omitempty"`
	Breakdowns                 []IncidentBreakdown        `json:"breakdowns,omitempty"`
	AffectedViewsPerHourOnOpen int64                      `json:"affected_views_per_hour_on_open,omitempty"`
	AffectedViewsPerHour       int64                      `json:"affected_views_per_hour,omitempty"`
	AffectedViews              int64                      `json:"affected_views,omitempty"`
}
